"""
Mainapp urls
"""
from django.urls import path

from mainapp.views import (RackDevicesApiView,
                           DepartmentListApiView,
                           RegionListApiView,
                           RegionDepartmentsListApiView,
                           SiteListApiView,
                           BuildingListApiView,
                           RoomListApiView,
                           SiteDetailApiView,
                           BuildingDetailApiView,
                           RoomDetailApiView,
                           SiteAddApiView,
                           SiteUpdateApiView,
                           SiteDeleteApiView,
                           BuildingAddApiView,
                           BuildingUpdateApiView,
                           BuildingDeleteApiView,
                           RoomAddApiView,
                           RoomUpdateApiView,
                           RoomDeleteApiView,
                           RackDetailApiView,
                           RackAddApiView,
                           RackUpdateApiView,
                           RackDeleteApiView,
                           DeviceAddApiView,
                           DeviceUpdateApiView,
                           DeviceDeleteApiView,
                           DeviceDetailApiView,
                           RackListApiView,
                           RackPartialListApiView,
                           UserApiView,
                           DeviceVendorsApiView,
                           DeviceModelsApiView,
                           RackVendorsApiView,
                           RackModelsApiView,
                           RacksReportApiView,
                           DevicesReportApiView,
                           DeviceLocationApiView,
                           RackLocationApiView,
                           TreeRegionApiView
                           )


urlpatterns = [
    path('user/', UserApiView.as_view()),
    path('tree/', TreeRegionApiView.as_view()),
    path('region/all/', RegionListApiView.as_view()),
    path('region/<int:pk>/departments/',
         RegionDepartmentsListApiView.as_view()),
    path('department/all/', DepartmentListApiView.as_view()),
    path('site/all/', SiteListApiView.as_view()),
    path('site/<int:pk>/', SiteDetailApiView.as_view()),
    path('site/create/', SiteAddApiView.as_view()),
    path('site/<int:pk>/update/', SiteUpdateApiView.as_view()),
    path('site/<int:pk>/delete/', SiteDeleteApiView.as_view()),
    path('building/all/', BuildingListApiView.as_view()),
    path('building/<int:pk>/', BuildingDetailApiView.as_view()),
    path('building/create/', BuildingAddApiView.as_view()),
    path('building/<int:pk>/update/', BuildingUpdateApiView.as_view()),
    path('building/<int:pk>/delete/', BuildingDeleteApiView.as_view()),
    path('room/all/', RoomListApiView.as_view()),
    path('room/<int:pk>/', RoomDetailApiView.as_view()),
    path('room/create/', RoomAddApiView.as_view()),
    path('room/<int:pk>/update/', RoomUpdateApiView.as_view()),
    path('room/<int:pk>/delete/', RoomDeleteApiView.as_view()),
    path('rack/all/', RackListApiView.as_view()),
    path('rack/all/partial/', RackPartialListApiView.as_view()),
    path('rack/<int:pk>/', RackDetailApiView.as_view()),
    path('rack/<int:pk>/location/', RackLocationApiView.as_view()),
    path('rack/create/', RackAddApiView.as_view()),
    path('rack/<int:pk>/update/', RackUpdateApiView.as_view()),
    path('rack/<int:pk>/delete/', RackDeleteApiView.as_view()),
    path('rack/<int:pk>/devices/', RackDevicesApiView.as_view()),
    path('rack/vendors/', RackVendorsApiView.as_view()),
    path('rack/models/', RackModelsApiView.as_view()),
    path('rack/report/', RacksReportApiView.as_view()),
    path('device/<int:pk>/', DeviceDetailApiView.as_view()),
    path('device/<int:pk>/location/', DeviceLocationApiView.as_view()),
    path('device/create/', DeviceAddApiView.as_view()),
    path('device/<int:pk>/update/', DeviceUpdateApiView.as_view()),
    path('device/<int:pk>/delete/', DeviceDeleteApiView.as_view()),
    path('device/vendors/', DeviceVendorsApiView.as_view()),
    path('device/models/', DeviceModelsApiView.as_view()),
    path('device/report/', DevicesReportApiView.as_view()),
]
