class Params:
    selenium_username = 'selenium'
    selenium_password = 'sel_testing'
    value_attr = 'value'
    building_name = 'Test building'
    room_name = 'Test room'
    rack_name = 'Test rack №1'
    site_name = 'Test_site_name'
    gecodriver_path = '/home/slunk/selenium/geckodriver'
    test_results_path = '/home/slunk/code/racks_project/e2e_tests/test_results'
    login_address = 'http://127.0.0.1:8000/login/'

    # Values
    first_device_first_unit_ok = '39'
    first_device_last_unit_ok = '39'
    second_device_first_unit_ok = '35'
    second_device_last_unit_ok = '36'
    first_device_first_unit_outside = '43'
    first_device_last_unit_outside = '44'
    first_device_first_unit_busy = '37'
    first_device_last_unit_busy = '36'
    rack_amount = '42'