class ReportMocks:
    racks_mock_data = [
        [2, 'Test_rack3', 40, 'Test_vendor3', 'Test_model3', '', 'Yes',
            '', '', '', '', '', '', '', None, None, None, 19, None,
            'Rack', 'Double frame', 'Floor standing', None, None, None,
            'Yes', 'No', '', '', 'Test_room1', 'Test_building1',
            'Test_site1', 'Test_department1', 'Test_region1',
            'http://127.0.0.1:8080/rack/2'],
        [1, 'Test_rack1', 40, 'Test_vendor1', 'Test_model1', '', 'Yes',
            '', '', '', '', '', '', '', None, None, None, 19, None,
            'Rack', 'Double frame', 'Floor standing', None, None, None,
            'Yes', 'No', '', '', 'Test_room1', 'Test_building1',
            'Test_site1', 'Test_department1', 'Test_region1',
            'http://127.0.0.1:8080/rack/1'],
        [3, 'Test_rack2', 20, 'Test_vendor2', 'Test_model2', '', 'No',
            '', '', '', '', '', '', '', None, None, None, 19, None,
            'Rack', 'Double frame', 'Floor standing', None, None, None,
            'Yes', 'No', '', '', 'Test_room2', 'Test_building2',
            'Test_site2', 'Test_department2', 'Test_region2',
            'http://127.0.0.1:8080/rack/3']
    ]
    devices_mock_data = [
        [4, 'Device active', 'Test_vendor4', 'Test_model4', '', '', '',
            'Our department', '', '', '', '', '', 7, 7, 'No', 'Other', '',
            None, None, None, '', 'IEC C14 socket', None, 220, 'AC', '', '',
            'Test_rack1', 'Test_room1', 'Test_building1', 'Test_site1',
            'Test_department1', 'Test_region1',
            'http://127.0.0.1:8080/device/4'],
        [3, 'Device active', 'Test_vendor3', 'Test_model3', '', '', '',
            'Our department', '', '', '', '', '', 3, 4, 'No', 'Other', '',
            None, None, None, '', 'IEC C14 socket', 50, 220, 'AC', '', '',
            'Test_rack1', 'Test_room1', 'Test_building1', 'Test_site1',
            'Test_department1', 'Test_region1',
            'http://127.0.0.1:8080/device/3'],
        [2, 'Device active', 'Test_vendor2', 'Test_model2', '', '', '',
            'Our department', '', '', '', '', '', 5, 5, 'Yes', 'Other', '',
            None, None, None, '', 'IEC C14 socket', 200, 220, 'AC', '', '',
            'Test_rack1', 'Test_room1', 'Test_building1', 'Test_site1',
            'Test_department1', 'Test_region1',
            'http://127.0.0.1:8080/device/2'],
        [1, 'Device active', 'Test_vendor1', 'Test_model1', '', '', '',
            'Our department', '', '', '', '', '', 2, 1, 'Yes', 'Other', '',
            None, None, None, '', 'IEC C14 socket', 100, 220, 'AC', '', '',
            'Test_rack1', 'Test_room1', 'Test_building1', 'Test_site1',
            'Test_department1', 'Test_region1',
            'http://127.0.0.1:8080/device/1'],
        [11, 'Device active', '', '', '', '', '',
            'Our department', '', '', '', '', '', 20, 20, 'No', 'Other', '',
            None, None, None, '', 'IEC C14 socket', None, 220, 'AC', '', '',
            'Test_rack2', 'Test_room2', 'Test_building2', 'Test_site2',
            'Test_department2', 'Test_region2',
            'http://127.0.0.1:8080/device/11'],
        [10, 'Device active', '', 'Test_model10', '', '', '',
            'Our department', '', '', '', '', '', 19, 19, 'No', 'Other', '',
            None, None, None, '', 'IEC C14 socket', None, 220, 'AC', '', '',
            'Test_rack2', 'Test_room2', 'Test_building2', 'Test_site2',
            'Test_department2', 'Test_region2',
            'http://127.0.0.1:8080/device/10'],
        [9, 'Device active', 'Test_vendor9', '', '', '', '',
            'Our department', '', '', '', '', '', 17, 17, 'No', 'Other', '',
            None, None, None, '', 'IEC C14 socket', None, 220, 'AC', '', '',
            'Test_rack2', 'Test_room2', 'Test_building2', 'Test_site2',
            'Test_department2', 'Test_region2',
            'http://127.0.0.1:8080/device/9'],
        [8, 'Device active', 'Test_vendor8', 'Test_model8', '', '', '',
            'Our department', '', '', '', '', '', 18, 18, 'No', 'Other', '',
            None, None, None, '', 'IEC C14 socket', None, 220, 'AC', '', '',
            'Test_rack2', 'Test_room2', 'Test_building2', 'Test_site2',
            'Test_department2', 'Test_region2',
            'http://127.0.0.1:8080/device/8'],
        [7, 'Device active', 'Test_vendor7', 'Test_model7', '', '', '',
            'Our department', '', '', '', '', '', 14, 13, 'No', 'Other', '',
            None, None, None, '', 'IEC C14 socket', None, 220, 'AC', '', '',
            'Test_rack2', 'Test_room2', 'Test_building2', 'Test_site2',
            'Test_department2', 'Test_region2',
            'http://127.0.0.1:8080/device/7'],
        [6, 'Device active', 'Test_vendor6', 'Test_model6', '', '', '',
            'Our department', '', '', '', '', '', 15, 15, 'Yes', 'Other', '',
            None, None, None, '', 'IEC C14 socket', None, 220, 'AC', '', '',
            'Test_rack2', 'Test_room2', 'Test_building2', 'Test_site2',
            'Test_department2', 'Test_region2',
            'http://127.0.0.1:8080/device/6'],
        [5, 'Device active', 'Test_vendor5', 'Test_model5', '', '', '',
            'Our department', '', '', '', '', '', 11, 12, 'Yes', 'Other', '',
            None, None, None, '', 'IEC C14 socket', None, 220, 'AC', '', '',
            'Test_rack2', 'Test_room2', 'Test_building2', 'Test_site2',
            'Test_department2', 'Test_region2',
            'http://127.0.0.1:8080/device/5']
    ]
